task14: refactoring
AlexPeshkov/Android_Netology pull request #13
Opened 2021-04-27 18:30 UTC by AlexPeshkov

2021-04-28 22:05 UTC, maks1596 requested changes

2021-04-28 22:05 UTC, maks1596 commented on app/sampledata/posts.json
> +      "published": "25 апреля в 18:30",
Обычно даты с сервера приходят в формате `ISO 8601` или в миллисекундах от 1970-го. Ваш вариант не правдоподобен. Ваш вариант не универсален - не пройдёт для английской локали. В Вашем варианте сервер задаёт правила отображения данных - это нарушает вышеописанные пункты.

2021-04-28 22:05 UTC, maks1596 commented on app/src/main/java/com/peshale/nmedia/activity/EditPostFragment.kt
> +            if (binding.etInputArea.text.isNullOrBlank()) {
Я думаю, поздно уже что-то менять, но всё же отмечу ключевые особенности реализации паттерна MVVM на данном обработчике нажатия.
1. Обработка нажатия сразу делегируется в модель представления.
2. В модели представление за счёт биндингов уже есть актуальное значение поля `etInputArea`.
3. На основе п.2 проверки валидности данных происходят в модели представления.
4. Результат проверки пробрасывается обратно на слой представления. Для этого используется либо
   1.  `SingleLiveEvent`, если событие одноразовое и не должно сохраняться,  
  либо 
    2. `LiveData`, если необходимо поменять состояние и обязательно его сохранить для последующего восстановления.
5. `postId` хранится в модели представления
6. Методы модели представления называются не в повелительном наклонении, а по событиям, обработчиками которых они и являются. Это связано с п.1.

2021-04-28 22:05 UTC, maks1596 commented on app/src/main/java/com/peshale/nmedia/activity/MainFragment.kt
> +                    putLong("postId", post.id)
1. Не хотите заменить на `navigation safeargs`?
2. Обычно такой код заносится внутрь статичной функции вызываемого экрана с целью единообразия кода в любом месте вызова экрана.

2021-04-28 22:05 UTC, maks1596 commented on app/src/main/java/com/peshale/nmedia/activity/PostCardFragment.kt
> +        var post = viewModel.searchPost(arguments?.get("postId") as Long)
1. Если что-то пойдёт не так (а оно обязательно пойдёт), то в данной строке мы получим как минимум `ClassCastException`. И не факт, что это будет правдой, потому что в данной строке у нас:
    1. может не быть `arguments`;
    2. может не быть `postId` в `arguments`;
    3. и только в последнюю очередь `postId` может быть совсем не `Long`.
С первыми двумя пунктами вам поможет функция `requireNotNull`. Поисследуйте как её можно применить.
2. Вызов `viewModel.searchPost(...)` не соответсвует философии паттернов MV*. Представление должно быть очень пассивное и сообщать о событиях, которые совершил пользователь. Далее в отложенным режиме в представлении будут вызваны методы, как реакция на данное событие. Как правильно:
    1. Передать в модель представления идентификатор поста.
    2. Подписаться на изменение поля `viewModel.post`.
    3. В обработчике изменений `viewModel.post` прозвести всю необходимую работу по заполению данными представления

2021-04-28 22:05 UTC, maks1596 commented on app/src/main/java/com/peshale/nmedia/activity/PostCardFragment.kt
> +            if (!post.likedByMe) {
Я уже видел данную логику в `MainFragment`, а значит этой логике место в каком-нибудь одном общем месте

2021-04-28 22:05 UTC, maks1596 commented on app/src/main/java/com/peshale/nmedia/dto/Post.kt
> +    @SerializedName("likedByMe")
Почему остальные поля не заслужили `@SerializedName`? Это абсолютно правильный ход зафиксировать имена полей независимо от их названия в коде. Таким образом будет не страшна обфускация.

2021-04-28 22:05 UTC, maks1596 commented on app/src/main/java/com/peshale/nmedia/repository/PostRepository.kt
> +    interface GetAllCallback {
А как же kotlin-овские `suspend` и `Result<T>`?

2021-04-28 22:05 UTC, maks1596 commented on app/src/main/java/com/peshale/nmedia/repository/PostRepository.kt
> +    interface GetPostCallback {
Аналогично комментарию выше к `GetAllCallback`

2021-04-28 22:05 UTC, maks1596 commented on app/src/main/java/com/peshale/nmedia/repository/PostRepositoryImpl.kt
> +                gson.fromJson(it, typePostToken.type)
Посчитайте сколько раз Вы написали один и тот же код, вынесите его в приватную функцию и вздохните с облегчением

2021-04-28 22:05 UTC, maks1596 commented on app/src/main/java/com/peshale/nmedia/vmodel/PostViewModel.kt
> +    var actualLikedByMe: MutableMap<Long, Boolean> = emptyMap<Long, Boolean>().toMutableMap()
Выберите, пожалуйста, что-то одно: либо `var`, либо `MutableMap`. Сразу оба зачастую избыточно и совершенно неконтролируемо с точки зрения мутабельности

2021-04-28 22:05 UTC, maks1596 commented on app/src/main/java/com/peshale/nmedia/vmodel/PostViewModel.kt
> +        _data.postValue(FeedModel(loading = true))
Судя по методу `loadPosts`, `FeedModel` - великолепный кандидат в `sealed class`. Переделайте, пожалуйста.
P.S.: На этом подходе всецело основан новый паттерн MVI

2021-04-28 22:05 UTC, maks1596 commented on app/src/main/java/com/peshale/nmedia/vmodel/PostViewModel.kt
> +        edited.value?.let {
```suggestion
        edited.value?.let { post ->
```
Тогда следующая строка кода не понадобится

2021-04-28 22:05 UTC, maks1596 commented on app/src/main/java/com/peshale/nmedia/vmodel/PostViewModel.kt
> +                    _data.value?.copy(posts = listOf(newPost) + _data.value?.posts as List<Post>)
Достаньте, пожалуйста, `data.value` один раз, положите в переменную и уже её проверьте на `null`. 
За счёт возможности асинхронной работы кода не стоит исключать тот факт, что `data.value?.copy(...)` вызовется, потому что в данный момента `data.value != null`, но спустя долю секунды значение `data` перезаписывается и инструкция `data.value?.posts as List<Post>` выбрасывает `ClassCastException`.

2021-04-28 22:05 UTC, maks1596 commented on app/src/main/java/com/peshale/nmedia/vmodel/PostViewModel.kt
> +    fun updatePost() {
Аналогичные методу `postCreation` замечания

2021-04-28 22:05 UTC, maks1596 commented on app/src/main/java/com/peshale/nmedia/vmodel/PostViewModel.kt
> +        if (edited.value?.content == text) {
Слишком много вопросительных знаков. Напишите в начале функции **один раз** следующий код и забудьте про "вопросики" до конца функции:
```kotlin
val editedValue = edited.value ?: return
```
Можете даже написать ещё жёстче, чтобы происходил не возврат из функции, но выброс исключения:
```kotlin
val editedValue = checkNotNull(edited.value) {
    "`edited.value` should be not null while content is changing"
}
```

2021-04-28 22:05 UTC, maks1596 commented on app/src/main/java/com/peshale/nmedia/vmodel/PostViewModel.kt
> +                .map { if (it.id != updatedPost.id) it else updatedPost.copy(likedByMe = actualLikedByMe[id]!!) }
Мы же знаем, что значение `actualLikedByMe[id]` существует и равно `true`. Зачем играть с судьбой, рисковать падением приложения, ловить в логи страшные NRE, которые обычно возникают на стыке Java и Kotlin, которых не должно быть в Kotlin, благодаря механизму `nullsafety`? Избегайте `!!`

2021-04-28 22:05 UTC, maks1596 commented on app/src/main/java/com/peshale/nmedia/vmodel/PostViewModel.kt
> +                .map { if (it.id != updatedPost.id) it else updatedPost.copy(likedByMe = actualLikedByMe[id]!!) }
Замечание аналогичное комментарию выше

2021-04-28 22:05 UTC, maks1596 commented on app/src/main/java/com/peshale/nmedia/vmodel/PostViewModel.kt
> +        return _data.value?.posts?.find { it.id == id }!!
Предположительно постов великое множество. Предположительно их настолько много, что они хранятся на сервере. Сервер у нас спрятан за интерфейсом репозитория. Сервер и должен производить эту предположительно сложную операцию поиска поста. А Вы для соблюдения чистоты кода должны убрать данную операцию за интерфейс репозитория

2021-04-28 22:05 UTC, maks1596 commented on app/src/main/res/layout/card_post.xml
> +<!--    <com.google.android.material.button.MaterialButton-->
Зачем комментировать, когда можно удалить и поддержать код в чистоте и легкочитаемом состоянии? Если Вам снова понадобится этот код, то его можно будет восстановить с помощью системы контроля версий Git

2021-04-28 22:05 UTC, maks1596 commented on app/src/main/res/layout/fragment_post_card.xml
> +<!--        <com.google.android.material.button.MaterialButton-->
Проще удалить закомментированный код. В предыдущем комментарии я постарался объяснить "почему" :)

2021-04-29 06:40 UTC, AlexPeshkov commented on app/sampledata/posts.json
> +      "published": "25 апреля в 18:30",
Спасибо за комментарий.
Для постов я определяю дату через https://github.com/AlexPeshkov/Android_Netology/blob/2f55fe4ac4c99d944c60cec25cd4f6374f3aafd7/app/src/main/java/com/peshale/nmedia/utils/AndroidUtils.kt#L34-L38

PostViewModel - > https://github.com/AlexPeshkov/Android_Netology/blob/2f55fe4ac4c99d944c60cec25cd4f6374f3aafd7/app/src/main/java/com/peshale/nmedia/vmodel/PostViewModel.kt#L34

Приведу дату в post.json к единому тогда формату

2021-05-07 13:20 UTC, closed without merging